#!/bin/bash -e

(( UID )) && exec sudo "$0" "$@"

config_file=/.ansibleconfig

if ! [[ -e $config_file ]]; then
    read -r -p 'Config: ' AS_CONFIG
    echo "$AS_CONFIG" > "$config_file"
fi

AS_CONFIG=$(cat "$config_file")
export AS_CONFIG

while true; do
    ansible-playbook -i localhost, "${0%/*}"/setup.yml
    rc=$?
    if (( PROMPT_RETRY )); then
        read -r -p "Retry? " REPLY
        [[ "$REPLY" == [yY]* ]] || break
    else
        exit "$rc"
    fi
done
