---
- name: Create local user for makepkg
  user: name=makepkg shell=/bin/sh

- name: Copy aur script
  copy: src=files/bin/aur dest=/usr/local/bin/aur mode=755

- name: Install base-devel
  pacman: name=base-devel state=present

- name: Install cower (pacaur AUR dep)
  aur: name=cower skip_installed=yes
  become: yes
  become_user: makepkg

- name: Install pacaur
  aur: name=pacaur skip_installed=yes
  become: yes
  become_user: makepkg
