---
- name: Install wireless tools
  when: wifi|bool
  pacman:
    name:
      - wpa_supplicant
      - dialog  # needed for wifi-menu

- template: src=files/hosts dest=/etc/hosts

- copy: src=files/bin/get-wired-interface dest=/usr/local/bin/get-wired-interface mode=755

- copy: src=files/bin/internet-isnt-crappy dest=/usr/local/bin/internet-isnt-crappy mode=755

- command: get-wired-interface
  register: wired_iface
  changed_when: false

- template: src=files/generic-wired dest=/etc/netctl/generic-wired
