---

- name: Install TLP
  pacman:
    name:
      - tlp

      # Determined from tlp-stat's suggestions at the end
      - acpi_call      # Adjust ThinkPad battery features

- name: Copy TLP config
  copy: src=files/tlp.conf dest=/etc/default/tlp

- name: Enable TLP services
  systemd: name={{ item }} enabled=yes masked=no
  with_items:
    - tlp
    - tlp-sleep

- name: Mask units conflicting with TLP
  systemd: name={{ item }} state=stopped masked=yes
  with_items:
    - systemd-rfkill.service
    - systemd-rfkill.socket

- name: Copy power key disable
  copy: src=files/logind.conf dest=/etc/systemd/logind.conf

- name: Copy power targets udev rule
  copy: src=files/udev/powertargets.rules dest=/etc/udev/rules.d/99-powertargets.rules

- name: Copy power targets
  copy: src=files/{{ item }}.target dest=/etc/systemd/system
  with_items:
    - ac
    - battery

# Sometimes Lin's W530 decides to totally freeze during suspend. A good suspend
# looks like this:
#
# Mar 18 21:46:32 daotian kernel: PM: suspend entry (deep)
# Mar 18 21:46:32 daotian kernel: PM: Syncing filesystems ... done.
#
# The bad one just sits here and stays powered on but unresponsive:
#
# Mar 19 15:14:04 daotian kernel: PM: suspend entry (deep)
#
# I suspect this is some weird timing/deadlock issue, so for now I've set
# pm_async=0 and it seems to work with no real penalty to suspend time. Bleh.
- name: Disable pm_async
  copy: src=files/disable-pm-async.conf dest=/etc/tmpfiles.d/disable-pm-async.conf
