---
- name: Install pyenv
  aur: name=pyenv skip_installed=yes
  become: yes
  become_user: makepkg

- name: Purge all Python 2 installations
  shell: "eval \"$(pyenv init -)\" && pyenv versions | sed 's/^..//' | awk '/^2/ { print $1 }' | tee >(xargs -L1 -r pyenv uninstall -f)"
  args:
    executable: /bin/bash
  register: py2
  become: yes
  become_user: "{{ user }}"
  changed_when: py2.stdout_lines

- name: Get active Python installed in pyenv
  shell: "eval \"$(pyenv init -)\" && pyenv version-name"
  register: pyenv_version
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- copy: src=files/bin/pyenv-check-rebuild-needed dest=/usr/local/bin/pyenv-check-rebuild-needed mode=755

- name: Check if Python needs a rebuild for dynamic lib update
  command: pyenv-check-rebuild-needed
  become: yes
  become_user: "{{ user }}"
  register: python_needs_force_rebuild
  ignore_errors: yes
  changed_when: false

- name: Install Python 3 using pyenv
  shell: "eval \"$(pyenv init -)\" && pyenv install {{ '-f' if python_needs_force_rebuild.rc != 0 }} {{ python_3_version }}"
  become: yes
  become_user: "{{ user }}"
  when: 'python_needs_force_rebuild.rc != 0 or python_3_version not in pyenv_version.stdout_lines'

- name: Get list of Python 3 utils installed
  shell: "eval \"$(pyenv init -)\" && pyenv shell {{ python_3_version }} && pip freeze --all | awk -F= '{ print $1 }'"
  register: py3_utils
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Python 3 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell {{ python_3_version }} && pip install -U {{ item }}'
  with_items:
    - pip
    - yturl
    - tzupdate
    - virtualenv
    - virtualenvwrapper
    - astroid
    - pylint
    - twine
    - jupyter
    - ipython
    - flake8
    - line-profiler
    - memory-profiler
    - psutil
    - awscli
    - tox
    - pipdeptree
    - srt
    - hanzidentifier  # for srt lines-matching -m hanzidentifier -f hanzidentifier.has_chinese
    - youtube-dl
    # lin's dev stuff
    - scipy
    - numpy
    - matplotlib
    - pandas
    - statsmodels
    - nbconvert
    - scikit-learn
    - numba
    - dask
    - cvxopt
    - graphviz
    - powerlaw
    - tabulate
    - htable
    - mutagen
    - networkx
    - black
    - certbot
    - gprof2dot
    - beets
    - codemod
    - whensthebus
    - csvprint
    - acestream-launcher
    - stapler
    - gsutil

    # s3cmd is busted on 2.0.2, which is latest release:
    - git+https://github.com/s3tools/s3cmd.git@a9375c33206312d118da7f3bfd62aad19c62cd2b
  become: yes
  become_user: "{{ user }}"
  when: 'not item.startswith("git+https://") and (item|basename) not in py3_utils.stdout_lines'
