---
- name: Install tkinter first so that we compile with tk support
  pacman: name=tk

- name: Install pyenv
  aur: name=pyenv skip_installed=yes
  become: yes
  become_user: makepkg

- name: Get list of Pythons installed in pyenv
  shell: "pyenv versions | sed 's/^..//' | awk '{ print $1 }'"
  register: pyenv_versions
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Pythons using pyenv
  command: "pyenv install {{ item }}"
  with_items:
    - "{{ python_2_version }}"
    - "{{ python_3_version }}"
  become: yes
  become_user: "{{ user }}"
  when: 'item not in pyenv_versions.stdout_lines'

- name: Get list of Python 3 utils installed
  shell: "eval \"$(pyenv init -)\" && pyenv shell {{ python_3_version }} && pip freeze | awk -F= '{ print $1 }'"
  register: py3_utils
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Get list of Python 2 utils installed
  shell: "eval \"$(pyenv init -)\" && pyenv shell {{ python_2_version }} && pip freeze | awk -F= '{ print $1 }'"
  register: py2_utils
  become: yes
  become_user: "{{ user }}"
  changed_when: false

- name: Install Python 3 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell {{ python_3_version }} && pip install {{ item }}'
  with_items:
    - yturl
    - tzupdate
    - virtualenv
    - virtualenvwrapper
    - astroid
    - pylint
    - twine
    - jupyter
    - ipython
    - flake8
    # God knows what this thing wants, it complains it wants Cython out of the
    # blue, but that doesn't help... let's look later.
    # - line_profiler
    - memory-profiler
    - psutil
    - awscli
    - tox
    - pipdeptree
    - srt
    - hanzidentifier  # for srt lines-matching -m hanzidentifier -f hanzidentifier.has_chinese
    - youtube-dl
    # lin's dev stuff
    - scipy
    - numpy
    - matplotlib
    - pandas
    - statsmodels
    - nbconvert
    - scikit-learn
    - numba
    - dask
    - cvxopt
    - graphviz
    - powerlaw
    - tabulate
    - htable
    - mutagen
    - networkx
    - black
    - certbot
    - gprof2dot
    - beets
    - codemod
  become: yes
  become_user: "{{ user }}"
  when: '(item|basename) not in py3_utils.stdout_lines'

- name: Install Python 2 utilities
  shell: 'eval "$(pyenv init -)" && pyenv shell {{ python_2_version }} && pip install {{ item }}'
  with_items:
    - gsutil
    - s3cmd
    - pipdeptree
    - stapler
    - flickr-download
  become: yes
  become_user: "{{ user }}"
  when: '(item|basename) not in py2_utils.stdout_lines'
