---
- pacman: name=rustup

- shell: "rustup show | awk -F- '$1 ~ /^[a-z]+$/ { print $1 }'"
  become: yes
  become_user: "{{ user }}"
  register: rust_versions
  changed_when: false

- name: Install rust toolchains
  command: "rustup install {{ item }}"
  with_items:
    - stable
    - nightly-2018-10-07  # pinned since clippy/rustfmt might not build on newer
  become: yes
  become_user: "{{ user }}"
  when: 'item not in rust_versions.stdout_lines'

- shell: "cargo install --list | awk '$0 ~ /^[a-zA-Z]/ { print $1 }'"
  become: yes
  become_user: "{{ user }}"
  register: cargo_pkgs
  changed_when: false

- shell: "rustup component list --toolchain nightly-2018-10-07 | awk -F- '{ print $1 \"-\" $2 }'"
  become: yes
  become_user: "{{ user }}"
  register: rustup_nightly_components
  changed_when: false

- shell: "rustup component list --toolchain stable | awk -F- '{ print $1 \"-\" $2 }'"
  become: yes
  become_user: "{{ user }}"
  register: rustup_stable_components
  changed_when: false

- name: Install libssh2-sys build dependency cmake
  pacman: name=cmake

- name: Install nightly rustup components
  command: "rustup component add {{ item }} --toolchain nightly-2018-10-07"
  with_items:
    - clippy-preview
  become: yes
  become_user: "{{ user }}"
  when: 'item not in rustup_nightly_components.stdout_lines'

- name: Install stable rustup components
  command: "rustup component add {{ item }} --toolchain stable"
  with_items:
    - rustfmt-preview
  become: yes
  become_user: "{{ user }}"
  when: 'item not in rustup_stable_components.stdout_lines'

- name: Install rust utilities
  command: "cargo install {{ item }}"
  with_items:
    - hyperfine
    - ripgrep
    - cargo-update
    - fd-find
    - cargo-edit-locally
  become: yes
  become_user: "{{ user }}"
  when: 'item not in cargo_pkgs.stdout_lines'
