---
- name: Copy udev settings for T460s
  copy: src=files/udev/t460s.rules dest=/etc/udev/rules.d/99-machinespec.rules
  when: model in ["T460s", "T470s", "X1 Carbon", "W530"]

- name: Copy udev settings for laptops
  copy: src=files/udev/laptop-net.rules dest=/etc/udev/rules.d/70-laptop-net.rules
  when: laptop

- name: Set I/O schedulers
  template: src=files/udev/io-schedulers.rules dest=/etc/udev/rules.d/99-io-schedulers.rules

- name: Set FUSE config
  copy: src=files/fuse.conf dest=/etc/fuse.conf

- copy: src=files/enable-thinkpad-fan-management dest=/etc/modprobe.d/enable-thinkpad-fan-management.conf

- name: Manually set fan
  copy: src=files/set-w530-fan.conf dest=/etc/tmpfiles.d/set-w530-fan.conf
  when: model in ["W530"]
