---
- name: Install WINE
  pacman:
    name:
      - lib32-libglvnd  # wine has multiple fulfilments for lib32-libgl
      - wine
      - wine_gecko
      - wine-mono
      # Audio
      - lib32-alsa-plugins
      - lib32-libpulse
      - lib32-openal
  when: install_wine

- name: Uninstall WINE
  pacman:
    state: absent
    extra_args: "--recursive"
    name:
      - wine
      - wine_gecko
      - wine-mono
      # Audio
      - lib32-libglvnd  # wine has multiple fulfilments for lib32-libgl
      - lib32-alsa-plugins
      - lib32-libpulse
      - lib32-openal
  when: not install_wine
